- name: Print Used Memory
  hosts: localhost
  tasks:
    - name: memory Good
      ansible.builtin.debug:
        msg: Memory Good
      when: ansible_memory_mb["real"]["used"] / ansible_memory_mb["real"]["total"] * 100 < 50

    - name: memory Orange
      ansible.builtin.debug:
        msg: Memory Good
      when: ansible_memory_mb["real"]["used"] / ansible_memory_mb["real"]["total"] * 100 > 50 and ansible_memory_mb["real"]["used"] / ansible_memory_mb["real"]["total"] * 100 < 70

    - name: memory Red
      ansible.builtin.debug:
        msg: Memory Red
      when: ansible_memory_mb["real"]["used"] / ansible_memory_mb["real"]["total"] * 100 < 70
